# SPDX-License-Identifier: Apache-2.0
# Copyright 2020 Intel Corporation
name: Docker image

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    env:
      DOCKER_REGISTRY: "docker.io/"
      DOCKER_REPOSITORY: "jayaramrcdac/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          make docker-build
          make docker-push

      # Cleanup space due to runners limited storage
      - name: Cleanup Docker images
        run: docker image prune -af